services:
  prefect_server:
    image: prefecthq/prefect:3-latest
    environment:
    # http://prefect-server:4200/api instead of localhost becasue localhost will refer to inside th docker container not the host machine
      - PREFECT_API_URL="${PREFECT_API_URL}"
      # 0.0.0.0 to allow access from outside the container
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:4200/api/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - prefect_network

  prefect-pool:
    build: .
    environment:
      - PREFECT_API_URL="${PREFECT_API_URL}"
    volumes:
      - ./reports:/opt/prefect/reports
    working_dir: /opt/prefect/app
    command: >
      bash -c "
      prefect pool create local-pool --concurrency-limit 1 --type process || true &&
      python -m src.pipeline.drift_check.py
      "
    networks:
      - prefect_network
    depends_on:
      prefect_server:
        condition: service_healthy  


  prefect-worker:
    build: .
    environment:
      - PREFECT_API_URL="${PREFECT_API_URL}"
    volumes:
      - ./reports:/opt/prefect/reports
    command: prefect worker start --pool local-pool
    networks:
      - prefect_network
    depends_on:
      prefect-pool:
        condition: service_completed_successfully

networks:
  prefect_network:
    driver: bridge

  