FROM python:3.12-slim

WORKDIR /app

COPY requirments-streamlit.txt .

RUN pip install --no-cache-dir -r requirments-streamlit.txt

COPY ui/app.py ./ui/
COPY ui/.streamlit ./.streamlit/

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "ui/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
