name: 'Air_Quality_System'

include:
  - compose-db.yaml
  - compose-kafka.yaml
  - compose-kafka-connect.yaml
  - compose-experiment-tracking.yaml
  - compose-prefect.yaml
  - compose-inference.yaml
  - compose-ui.yaml
  - compose-nginx.yaml
  - infra/monitoring/grafana/compose-grafana.yaml
  - infra/monitoring/alloy/compose-alloy.yaml
  - infra/monitoring/loki/compose-loki.yaml
  - infra/monitoring/prometh/compose-prometheus.yaml
