services:

  # problem of loki need permission to chumks
  loki-setup:
    image: alpine
    profiles: ["monitoring"]
    container_name: loki-setup
    volumes:
      - chunks:/loki/chunks
    command: chown -R 10001:10001 /loki/chunks # the rule also must be writtin here when needed

  loki:
    image: grafana/loki:latest

    profiles: ["monitoring"]

    container_name: loki

    restart: unless-stopped

    ports:
      - "3100:3100"

    networks:
      - prefect_network
      - default

    depends_on:
      loki-setup:
        condition: service_completed_successfully

    healthcheck:
      test: ["CMD", "/usr/bin/loki", "-health"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - chunks:/loki/chunks
      # - rules_directory: /loki/rules
      - ./config/loki_config.yaml:/etc/loki/config.yaml

    command:
      - "-config.file=/etc/loki/config.yaml"
      - "-print-config-stderr"

volumes:
  chunks:
