{
 "title": "Air Pollution",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Prefect Worker",
   "type": "logs",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"air_quality_system-prefect-worker-1\"}"
    }
   ]
  },
  {
   "title": "Main FLow",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"air_quality_system-main_flow-1\"} |= ``"
    }
   ]
  },
  {
   "title": "container_cpu_usage_seconds_total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{ }[$__rate_interval]))",
     "legendFormat": "sum(rate)"
    }
   ]
  },
  {
   "title": "container_fs_usage_bytes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_fs_usage_bytes{ })",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "container_blkio_device_usage_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(container_blkio_device_usage_total{ }[$__rate_interval]))",
     "legendFormat": "sum(rate)"
    }
   ]
  },
  {
   "title": "container_cpu_system_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{ }[$__rate_interval]))",
     "legendFormat": "sum(rate)"
    }
   ]
  },
  {
   "title": "container_memory_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_failures_total{ }[$__rate_interval]))",
     "legendFormat": "sum(rate)"
    }
   ]
  },
  {
   "title": "container_cpu_load_average_10s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(container_cpu_load_average_10s{ })",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}