apiVersion: 1

datasources:
  - name: air_pollution
    orgId: 1
    type: postgres
    isDefault: true
    url: db:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      database: postgres
      postgresVersion: 1700
