apiVersion: 1

datasources:
  - name: air_pollution
    orgId: 1
    type: postgres
    isDefault: true
    url: db:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      database: postgres
      postgresVersion: 1700

  - name: Loki
    orgId: 1
    type: loki
    access: proxy
    url: 'http://loki:3100'
    basicAuth: false
    version: 1
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true # allows you to create and manage alerts directly inside the Grafana UI.
      # allowAsRecordingRulesTarget: true
      # disableRecordingRules: false
      timeInterval: 10s
